/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import instance.Instance;
import instance.Request;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solution.Solution;
import solution.Tournee;
import solution.TourneeTech;
import solveur.Ajout;
import solveur.InsertionPPV;
import solveur.RechercheLocale;
import solveur.Solveur;
import solveur.Trivial;

/**
 *
 * @author othma
 */
public class Solutions extends javax.swing.JFrame {

    Instance instance;
    Solution solution;
    
    /**
     * Creates new form Solutions
     */
    public Solutions() {
        initComponents();
    }
    
    public Solutions(Instance i){
        initComponents();
       initialisationFenetre();
        instance = i;
        solution = null;
        remplirJlabel();
        remplirJtext();
        
        
    }
    
    private void initialisationFenetre(){
        setSize(1000,720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(810, 610));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jButton1.setText("Trivial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ajout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Plus Proche Voisin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        jTextField8.setText("jTextField8");

        jTextField9.setText("jTextField9");

        jTextField10.setText("jTextField10");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Graphique");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Recherche locale");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Arborescence");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Comparer Couts");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(64, 64, 64)
                .addComponent(jButton3)
                .addGap(54, 54, 54)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8)
                    .addComponent(jTextField9)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButton4)
                        .addGap(43, 43, 43)
                        .addComponent(jButton6)
                        .addGap(35, 35, 35)
                        .addComponent(jButton7)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modificationJlabel();
        modificationJtext3();
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String [] colNames = {"Jour","Number of trucks","Number of technicians"};
        dt.setColumnIdentifiers(colNames);
        Map<Integer,LinkedList<Tournee>> liste = solution.getListeTournees();
        if (dt.getRowCount() !=0){
            dt.setRowCount(0);
        }
        for (int i = 1; i<=solution.getInstance().getDays();i++){
            
				LinkedList<Tournee> tournees = liste.get(i);
				LinkedList<Tournee> truck = new LinkedList<>();
				int nbTruck = 0;
				LinkedList<Tournee> tech = new LinkedList<>();
				LinkedList<Integer> technician = new LinkedList<>();
				int nbTech = 0;
				if(tournees != null) {
					for (Tournee t : tournees) {
						if (t instanceof TourneeTech) {
							tech.add(t);
							if(!technician.contains(((TourneeTech) t).getTechnician().getIdTechnician())){
								technician.add(((TourneeTech) t).getTechnician().getIdTechnician());
								nbTech++;
							}
						} else {
							truck.add(t);
							nbTruck++;
						}
					}
				}
				dt.addRow(new Object[]{i,nbTruck,nbTech});
				
				
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modificationJlabel();
        modificationJtext();
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String [] colNames = {"Jour","Number of trucks","Number of technicians"};
        dt.setColumnIdentifiers(colNames);
        Map<Integer,LinkedList<Tournee>> liste = solution.getListeTournees();
        if (dt.getRowCount() !=0){
            dt.setRowCount(0);
        }
        for (int i = 1; i<=solution.getInstance().getDays();i++){
            
				LinkedList<Tournee> tournees = liste.get(i);
				LinkedList<Tournee> truck = new LinkedList<>();
				int nbTruck = 0;
				LinkedList<Tournee> tech = new LinkedList<>();
				LinkedList<Integer> technician = new LinkedList<>();
				int nbTech = 0;
				if(tournees != null) {
					for (Tournee t : tournees) {
						if (t instanceof TourneeTech) {
							tech.add(t);
							if(!technician.contains(((TourneeTech) t).getTechnician().getIdTechnician())){
								technician.add(((TourneeTech) t).getTechnician().getIdTechnician());
								nbTech++;
							}
						} else {
							truck.add(t);
							nbTruck++;
						}
					}
				}
				dt.addRow(new Object[]{i,nbTruck,nbTech});
				
				
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        modificationJlabel();
        modificationJtext2();
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String [] colNames = {"Jour","Number of trucks","Number of technicians"};
        dt.setColumnIdentifiers(colNames);
        if (dt.getRowCount() !=0){
            dt.setRowCount(0);
        }
        Map<Integer,LinkedList<Tournee>> liste = solution.getListeTournees();
        for (int i = 1; i<=solution.getInstance().getDays();i++){
            
				LinkedList<Tournee> tournees = liste.get(i);
				LinkedList<Tournee> truck = new LinkedList<>();
				int nbTruck = 0;
				LinkedList<Tournee> tech = new LinkedList<>();
				LinkedList<Integer> technician = new LinkedList<>();
				int nbTech = 0;
				if(tournees != null) {
					for (Tournee t : tournees) {
						if (t instanceof TourneeTech) {
							tech.add(t);
							if(!technician.contains(((TourneeTech) t).getTechnician().getIdTechnician())){
								technician.add(((TourneeTech) t).getTechnician().getIdTechnician());
								nbTech++;
							}
						} else {
							truck.add(t);
							nbTruck++;
						}
					}
				}
				dt.addRow(new Object[]{i,nbTruck,nbTech});
				
				
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(solution == null){
            JOptionPane.showMessageDialog(this, "Veuillez calculer une solution préalablement");
        }
        else {
           GraphiqueVisuel gv = new GraphiqueVisuel(solution);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        modificationJlabel();
        modificationJtext4();
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        String [] colNames = {"Jour","Number of trucks","Number of technicians"};
        dt.setColumnIdentifiers(colNames);
        if (dt.getRowCount() !=0){
            dt.setRowCount(0);
        }
        Map<Integer,LinkedList<Tournee>> liste = solution.getListeTournees();
        for (int i = 1; i<=solution.getInstance().getDays();i++){
            
				LinkedList<Tournee> tournees = liste.get(i);
				LinkedList<Tournee> truck = new LinkedList<>();
				int nbTruck = 0;
				LinkedList<Tournee> tech = new LinkedList<>();
				LinkedList<Integer> technician = new LinkedList<>();
				int nbTech = 0;
				if(tournees != null) {
					for (Tournee t : tournees) {
						if (t instanceof TourneeTech) {
							tech.add(t);
							if(!technician.contains(((TourneeTech) t).getTechnician().getIdTechnician())){
								technician.add(((TourneeTech) t).getTechnician().getIdTechnician());
								nbTech++;
							}
						} else {
							truck.add(t);
							nbTruck++;
						}
					}
				}
				dt.addRow(new Object[]{i,nbTruck,nbTech});
				
				
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         if(solution == null){
            JOptionPane.showMessageDialog(this, "Veuillez calculer une solution préalablement");
        }
        else {
          Affichage af = new Affichage(this.solution);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
        SolutionCompare sc = new SolutionCompare(instance);
    }//GEN-LAST:event_jButton7ActionPerformed
 public void modificationJlabel(){
        jLabel1.setText("DATASET");
        jLabel2.setText("NAME");
        jLabel3.setText("TRUCK DIST");
        jLabel4.setText("NUM TRUCK DAYS");
        jLabel5.setText("NUM TRUCKS USED");
        jLabel6.setText("TECHNICIAN DIST");
        jLabel7.setText("NUM TECHNICIAN DAYS");
        jLabel8.setText("NUM TECHNICIANS USED");
        jLabel9.setText("IDLE MACHINE COSTS");
        jLabel10.setText("TOTAL COST");
    }
    public void remplirJlabel(){
        jLabel1.setText("DATASET");
        jLabel2.setText("NAME");
        jLabel3.setText("DAYS");
        jLabel4.setText("TRUCK CAP");
        jLabel5.setText("TRUCK DIS COST");
        jLabel6.setText("TRUCK DAY COST");
        jLabel7.setText("TRUCK COST");
        jLabel8.setText("TECH DISTANCE COST");
        jLabel9.setText("TECH DAY COST");
        jLabel10.setText("TECH COST");
    }
    
    public void modificationJtext(){
        Solveur solvT = new Ajout();
        solution = solvT.solve(instance);
        jTextField1.setText(solution.getInstance().getDataset());
        jTextField2.setText(solution.getInstance().getNom());
        jTextField3.setText(String.valueOf(solution.getTruckDistance()));
        jTextField4.setText(String.valueOf(solution.getNumberTruckDays()));
        jTextField5.setText(String.valueOf(solution.getNumberTrucksUsed()));
        jTextField6.setText(String.valueOf(solution.getTechnicianDistance()));
        jTextField7.setText(String.valueOf(solution.getNumberTechnicianDays()));
        jTextField8.setText(String.valueOf(solution.getNumberTechniciansUsed()));
        jTextField9.setText(String.valueOf(solution.getMachineCost()));
        jTextField10.setText(String.valueOf(solution.getCoutTotal()));
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
    }
     public void modificationJtext2(){
        Solveur solvT = new InsertionPPV();
        solution = solvT.solve(instance);
        jTextField1.setText(solution.getInstance().getDataset());
        jTextField2.setText(solution.getInstance().getNom());
        jTextField3.setText(String.valueOf(solution.getTruckDistance()));
        jTextField4.setText(String.valueOf(solution.getNumberTruckDays()));
        jTextField5.setText(String.valueOf(solution.getNumberTrucksUsed()));
        jTextField6.setText(String.valueOf(solution.getTechnicianDistance()));
        jTextField7.setText(String.valueOf(solution.getNumberTechnicianDays()));
        jTextField8.setText(String.valueOf(solution.getNumberTechniciansUsed()));
        jTextField9.setText(String.valueOf(solution.getMachineCost()));
        jTextField10.setText(String.valueOf(solution.getCoutTotal()));
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
    }
      public void modificationJtext3(){
        Solveur solvT = new Trivial();
        solution = solvT.solve(instance);
        jTextField1.setText(solution.getInstance().getDataset());
        jTextField2.setText(solution.getInstance().getNom());
        jTextField3.setText(String.valueOf(solution.getTruckDistance()));
        jTextField4.setText(String.valueOf(solution.getNumberTruckDays()));
        jTextField5.setText(String.valueOf(solution.getNumberTrucksUsed()));
        jTextField6.setText(String.valueOf(solution.getTechnicianDistance()));
        jTextField7.setText(String.valueOf(solution.getNumberTechnicianDays()));
        jTextField8.setText(String.valueOf(solution.getNumberTechniciansUsed()));
        jTextField9.setText(String.valueOf(solution.getMachineCost()));
        jTextField10.setText(String.valueOf(solution.getCoutTotal()));
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
    }
      
      public void modificationJtext4(){
        Solveur solvRl = new RechercheLocale();
        solution = solvRl.solve(instance);
        jTextField1.setText(solution.getInstance().getDataset());
        jTextField2.setText(solution.getInstance().getNom());
        jTextField3.setText(String.valueOf(solution.getTruckDistance()));
        jTextField4.setText(String.valueOf(solution.getNumberTruckDays()));
        jTextField5.setText(String.valueOf(solution.getNumberTrucksUsed()));
        jTextField6.setText(String.valueOf(solution.getTechnicianDistance()));
        jTextField7.setText(String.valueOf(solution.getNumberTechnicianDays()));
        jTextField8.setText(String.valueOf(solution.getNumberTechniciansUsed()));
        jTextField9.setText(String.valueOf(solution.getMachineCost()));
        jTextField10.setText(String.valueOf(solution.getCoutTotal()));
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
      }
    public void remplirJtext(){
        jTextField1.setText(instance.getDataset());
        jTextField2.setText(instance.getNom());
        jTextField3.setText(String.valueOf(instance.getDays()));
        jTextField4.setText(String.valueOf(instance.getTruckCapacity()));
        jTextField5.setText(String.valueOf(instance.getTruckDistanceCost()));
        jTextField6.setText(String.valueOf(instance.getTruckDayCost()));
        jTextField7.setText(String.valueOf(instance.getTruckCost()));
        jTextField8.setText(String.valueOf(instance.getTechnicianDistanceCost()));
        jTextField9.setText(String.valueOf(instance.getTechnicianDayCost()));
        jTextField10.setText(String.valueOf(instance.getTechnicianCost()));
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solutions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
