package operateur;

public enum TypeOperateurLocal {
    INTER_DEPLACEMENT_TRUCK,
    /*INTER_ECHANGE_TRUCK,
    INTER_DEPLACEMENT_TECH,
    INTER_ECHANGE_TECH,*/
    INTRA_ECHANGE_TRUCK,
    INTRA_DEPLACEMENT_TRUCK,
    INTRA_DEPLACEMENT_TECH,
    INTRA_ECHANGE_TECH
}
